{pkgs, ...}: {
  wayland.windowManager.hyprland = {
    enable = true;
    package = pkgs.hyprland;
    xwayland = {
      enable = true;
    };
    settings = {
      autogenerated = 0;

      "$terminal" = "ghostty";
      "$fileManager" = "nautilus";
      "$menu" = "wofi --show drun";
      "$LAPTOP_KB_ENABLED" = true;

      monitor = [
        "eDP-1,1920x1080,auto,1"
        ",preferred,auto,1"
      ];

      device = {
        name = "at-translated-set-2-keyboard";
        enabled = "$LAPTOP_KB_ENABLED";
      };

      exec-once = [
        "waybar &"
        "waypaper --restore &"
      ];

      env = [
        "ELECTRON_OZONE_PLATFORM_HINT,auto"
        "LIBVA_DRIVER_NAME,nvidia"
        "__GLX_VENDOR_LIBRARY_NAME,nvidia"
        "XCURSOR_SIZE,24"
        "XCURSOR_THEME,WhiteSur-cursors"
        "HYPRCURSOR_SIZE,24"
      ];

      general = {
        gaps_in = 2;
        gaps_out = 2;

        border_size = 1;

        "col.active_border" = "rgba(5e5e5ecc)";
        "col.inactive_border" = "rgba(3a3a3a99)";

        resize_on_border = true;
        allow_tearing = false;
        layout = "dwindle";
      };

      decoration = {
        rounding = 2;
        active_opacity = 1.0;
        inactive_opacity = 1.0;

        shadow = {
          enabled = true;
          range = 8;
          render_power = 2;
          color = "rgba(00000055)";
        };

        blur = {
          enabled = false;
        };
      };

      animations = {
        enabled = true;

        bezier = [
          "superSmoothIn, 0.9, 0, 0.1, 1"
          "superSmoothOut, 0.1, 0, 0.9, 1"
          "superSmoothInOut, 0.95, 0, 0.05, 1"
        ];

        animation = [
          "global, 1, 3.5, superSmoothInOut"
          "windows, 1, 0.5, superSmoothInOut"
          "windowsIn, 1, 0.6, superSmoothIn, slide"
          "windowsOut, 1, 0.6, superSmoothOut, slide"
          "workspaces, 1, 1.0, superSmoothInOut, slide"
          "fadeIn, 1, 0.3, superSmoothIn"
          "fadeOut, 1, 0.3, superSmoothOut"
          "layers, 1, 0.6, superSmoothInOut"
          "layersIn, 1, 0.6, superSmoothIn, slide"
          "layersOut, 1, 0.6, superSmoothOut, slide"
          "fadeLayersIn, 1, 0.4, superSmoothIn"
          "fadeLayersOut, 1, 0.4, superSmoothOut"
        ];
      };

      dwindle = {
        pseudotile = true;
        preserve_split = true;
      };

      master = {
        new_status = "master";
      };

      misc = {
        force_default_wallpaper = 0;
        disable_hyprland_logo = true;
        vfr = true;
      };

      input = {
        kb_layout = "us";
        kb_variant = "";
        kb_model = "";
        kb_options = "";
        kb_rules = "";

        follow_mouse = 1;
        force_no_accel = true;
        natural_scroll = true;

        repeat_rate = 30;
        repeat_delay = 300;

        touchpad = {
          natural_scroll = true;
        };
      };

      gestures = {
        workspace_swipe = true;
      };

      "$mainMod" = "Alt";

      bind = [
        "$mainMod, T, exec, $terminal"
        "$mainMod, Q, killactive, "
        "$mainMod, E, exec, $fileManager"
        "$mainMod, V, togglefloating, "
        "$mainMod, Space, exec, $menu"
        "$mainMod, P, pseudo, "
        "$mainMod, J, togglesplit"

        "SUPER_SHIFT, R, exec, hyprctl reload"
        ", Print, exec, grimblast --notify copy area"
        "$mainMod, P, exec, grimblast --notify copy area"

        "$mainMod SHIFT, H, movefocus, l"
        "$mainMod SHIFT, L, movefocus, r"
        "$mainMod SHIFT, K, movefocus, u"
        "$mainMod SHIFT, J, movefocus, d"

        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
        "$mainMod, 0, workspace, 10"

        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"

        "$mainMod, S, togglespecialworkspace, magic"
        "$mainMod SHIFT, S, movetoworkspace, special:magic"

        "$mainMod, mouse_down, workspace, e+1"
        "$mainMod, mouse_up, workspace, e-1"
      ];

      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];

      bindel = [
        ",XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
        ",XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
        ",XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
        ",XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"
        ",XF86MonBrightnessUp, exec, brightnessctl s 10%+"
        ",XF86MonBrightnessDown, exec, brightnessctl s 10%-"
      ];

      bindl = [
        ", XF86AudioNext, exec, playerctl next"
        ", XF86AudioPause, exec, playerctl play-pause"
        ", XF86AudioPlay, exec, playerctl play-pause"
        ", XF86AudioPrev, exec, playerctl previous"
      ];

      windowrule = [];

      windowrulev2 = [
        "float,class:org\.gnome\.Nautilus"
        "suppressevent maximize, class:.*"
        "float,class:xdg-desktop-portal-gtk,title:.*wants to open"
        "nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0"
      ];
    };
  };
}
