{pkgs, ...}: {
  home = {
    packages = with pkgs; [
      (writeScriptBin "cow" ''
        #!/usr/bin/env bash
        cowsay $(fortune)
      '')
      newsflash
      (prismlauncher.override {jdks = [jdk8 jdk17 jdk21];})
      (discord.override { withVencord = true; })
      slack
      remmina
      nwg-displays
      escrotum
      ngrok
      lazygit
      bc
      stremio
      redis
      waypaper
      brave
      firefox
      gh
      gparted
      spotify
      libreoffice
      obsidian
      playerctl
      tmux
      nnn
      zip
      xz
      unzip
      p7zip
      ripgrep
      jq
      yq-go
      eza
      fzf
      mtr
      iperf3
      dnsutils
      ldns
      aria2
      socat
      nmap
      ipcalc
      cowsay
      fortune
      file
      which
      tree
      gnused
      gnutar
      gawk
      zstd
      gnupg
		  gnumake
      nix-output-monitor
      glow
      btop
      iotop
      iftop
      strace
      ltrace
      lsof
      sysstat
      lm_sensors
      ethtool
      pciutils
      usbutils
      go
      zig
      bun
      cmake
      clang
      rustup
      nodejs
      python3
      pyenv
      corepack
      obs-studio
      obs-studio-plugins.wlrobs
      mkcert
      obs-studio-plugins.obs-pipewire-audio-capture
      zls
      gopls
      pyright
      marksman
      lua-language-server
      golangci-lint
      golangci-lint-langserver
      vscode-langservers-extracted
      typescript-language-server
      tailwindcss-language-server
      svelte-language-server
      markdownlint-cli
      nixfmt-classic
      alejandra
      nixd
      nil
      grimblast
      grim
      slurp
      whitesur-cursors
      graphite-gtk-theme
      papirus-icon-theme
      nwg-look
    ];
  };
}
